### ISSUE TITLE
6tisch centralized scheduling algorithm

### ISSUE THREAD

**Issue by aaa-engi** [imec-idlab/6tisch-simulator-extended#1]
I am new in 6tisch
how i can add an centralized scheduling algorithm to 6tisch?
do you have sample for it?
please help me...

**Comment by emunicio** [comment]
Hi @aaa-engi, 
This versión of the simulator does not have a centralized scheduling algorithm, just a version of DeBraA (which is decentralized).

However you can easily implement a centralized scheduling algorithm by installing the schedules in the nodes from a function, or using a specific protocol to do it in a more realistic way.

By the way, you may want to use the new version of the simulator:
https://bitbucket.org/6tisch/simulator

Kind regards

**Comment by aaa-engi** [comment]
> 
> 
> Hi @aaa-engi,
> This versión of the simulator does not have a centralized scheduling algorithm, just a version of DeBraA (which is decentralized).
> 
> However you can easily implement a centralized scheduling algorithm by installing the schedules in the nodes from a function, or using a specific protocol to do it in a more realistic way.
> 
> By the way, you may want to use the new version of the simulator:
> https://bitbucket.org/6tisch/simulator
> 
> Kind regards

Thank you...
for centralized scheduling algorithm , 
Should i write a function to manage schedules in nodes in "sf.py" in new version of simulator or in another files such as "sixp.py"?
Do you have a sample about centralized scheduling for help?
