### ISSUE TITLE
6tisch 

### ISSUE THREAD

**Issue by aaa-engi** [imec-idlab/6tisch-simulator-extended#2]
@emunicio 
Thank you...
Yes i have simulator from bitbucket website
but for centralized scheduling algorithm ,
Should i write a function to manage schedules in nodes in "sf.py" in new version of simulator or in another files such as "sixp.py"?
Do you have a sample code for centralized scheduling?

**Comment by emunicio** [comment]
Yes, you can manage the schedules in the sf.py, (where the scheduling function is implemented).
Sixp.py would be the code for implementing 6Top Protocol, a distributed scheduling protocol for 6TiSCH.
Unfortunatedly I don't have a centralized scheduling sample, however in this repository you can see the "opt2" mode, in Mote.py, where scheduling is performed as if all nodes know the cell usage of the other nodes in the network (as in a centralized entity).
